import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '快速开始',
      collapsed: false,
      items: [
        'intro',
      ],
    },
    {
      type: 'category',
      label: '核心概念',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'core',
        },
      ],
    },
    {
      type: 'category',
      label: '模块参考',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules',
        },
      ],
    },
    {
      type: 'category',
      label: 'API参考',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

export default sidebars;
